
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: R-Blog
  username: Ibu
  password: ibuPostData1749%
  host: localhost


test:
  <<: *default
  database: R-Blog
  username: Ibu
  password: ibuPostData1749%
  host: localhost

production:
  <<: *default
  database: R-Blog
  username: Ibu
  password: ibuPostData1749%
  host: localhost
